apiVersion: apps/v1
kind: Deployment
metadata:
  name: rack-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rack-app
  template:
    metadata:
      labels:
        app: rack-app
    spec:
      containers:
        - name: rack-app
          image: rack-app:deploy-$COMMITISH
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /
              port: 9292
          livenessProbe:
            httpGet:
              path: /
              port: 9292
            initialDelaySeconds: 2
            periodSeconds: 5
